
# Setup

# Edit these fields for your project 

title:            'Open Contractors'
tagline:          'Making Sense of Government Contracting'
description:      'An online <a href="http://jekyllrb.com" target="_blank">open-source</a> platform for searching, analyzing and making sense of government procurement data.'
url:              'http://open.contractors'
baseurl:          /

author:
  name:           'Allison McCartney'
  url:            'https://twitter.com/anmccartney'

google-fonts:
  title:          'Open Sans'
  body:           'Gentium Book Basic'

social:
  - type:         'github'
    url:          'https://github.com/poole/hyde'
  - type:         'twitter'
    url:          'https://twitter.com/opencontractors'



# Style options
# 
# Currently, the site uses a default theme. If you would like to change the color scheme, copy
# one of the themes listed below and paste it next to 'base-theme: '
# 
# For example--
# base-theme: 'theme-base-0c'
# 
# red:        'theme-base-08'
# orange:     'theme-base-09'
# peach:      'theme-base-0a'
# green:      'theme-base-0b'
# aqua:       'theme-base-0c'
# light blue: 'theme-base-0d'
# purple:     'theme-base-0e'
# brown:      'theme-base-0f'


base-theme:


# Don't edit any of the below fields

port:             4444

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty